# Generated by Django 2.2.20 on 2021-09-21 10:39

from django.db import migrations

import phonenumbers


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if not flat.owner_pure_phone:
            pure_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')
            if phonenumbers.is_valid_number(pure_phonenumber):
                flat.owner_pure_phone = phonenumbers.format_number(
                    pure_phonenumber,
                    phonenumbers.PhoneNumberFormat.E164
                )
                flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers)
    ]
