# Generated by Django 2.2.20 on 2021-09-27 18:21

from django.db import migrations


def connect_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all():
        flats = Flat.objects.filter(
            owners_phonenumber=owner.owners_phonenumber,
            owner=owner.full_name
        )
        owner.flats.set(flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20210921_1515'),
    ]

    operations = [
        migrations.RunPython(connect_flats_to_owners)
    ]
