# Generated by Django 2.2.20 on 2021-09-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20210921_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='full_name'
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber'
        ),
        migrations.RemoveField(
            model_name='flat',
            name=''
        ),
        migrations.RemoveField(
            model_name='flat',
            name=''
        ),
    ]
